import { useRef, useState } from 'react'
import { Bot, CheckCircle2, ChevronRight, Database, FileText, GitBranch, LoaderCircle, Play, Search, Settings, ShieldCheck, Sparkles, Upload, Wand2 } from 'lucide-react'
import Sidebar from './frontend/components/Sidebar'
import DataTable from './frontend/components/DataTable'

const api = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const nav = ['Overview', 'Profile', 'Quality', 'Cleaning', 'Analysis', 'AI Analyst', 'SQL', 'Reports', 'Versions', 'Lineage']

function App() {
  const [data, setData] = useState(null), [page, setPage] = useState('Overview'), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const [question, setQuestion] = useState(''), [answer, setAnswer] = useState(null), [sql, setSql] = useState('SELECT * FROM dataset LIMIT 20'), [result, setResult] = useState(null), [version, setVersion] = useState(null)
  const input = useRef()
  async function upload(file) {
    if (!file) return
    setBusy(true); setMessage('Reading your file and building its data profile…')
    try { const fd = new FormData(); fd.append('file', file); const r = await fetch(`${api}/api/datasets`, { method: 'POST', body: fd }); if (!r.ok) throw new Error('We could not read this file. Try a CSV, Excel, JSON, or Parquet file.'); const result = await r.json(); setData(result); setMessage('Your dataset is ready. Start with its profile or data quality checks.'); setPage('Overview') } catch (e) { setMessage(e.message) } finally { setBusy(false) }
  }
  async function ask() { if (!question.trim()) return; setBusy(true); try { const r = await fetch(`${api}/api/chat`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({question, dataset_id:data.dataset_id, context:{profile:data}}) }); const res = await r.json(); if (/429|quota|resource_exhausted/i.test(res.answer || '')) res.answer = 'The AI provider is temporarily unavailable. Your dataset is safe; try again shortly or use the SQL workspace.'; setAnswer(res); setQuestion('') } finally { setBusy(false) } }
  async function transform(operation) { setBusy(true); setMessage('Creating a separate cleaned version…'); try { const r = await fetch(`${api}/api/datasets/${data.dataset_id}/transformations/${operation}/execute`, {method:'POST'}); const res = await r.json(); if(!res.ok) throw new Error(res.detail||'Could not create this version.'); setVersion(res); setMessage(`${operation.replace('_',' ')} finished. Review or download the new CSV below.`); } catch(e){setMessage(e.message)} finally { setBusy(false) } }
  async function validateSql() { setBusy(true); try { const r = await fetch(`${api}/api/sql/execute`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset_id:data.dataset_id,query:sql})}); const res = await r.json(); if(!r.ok) throw new Error(res.detail||'This query could not run.'); setResult(res); setMessage(`${res.count} rows returned from your active dataset.`) } catch(e){setMessage(e.message)} finally{setBusy(false)} }
  if (!data) return <Welcome busy={busy} message={message} input={input} upload={upload}/>
  return <div className="product"><Sidebar data={data} nav={nav} page={page} setPage={setPage} reset={() => {setData(null);setMessage('')}}/><main><header><div><p className="eyebrow">ACTIVE DATASET</p><h2>{data.file_name}</h2></div><button className="quiet" onClick={()=>{setData(null);setMessage('')}}>Change dataset</button></header>{message && <div className="notice"><CheckCircle2 size={17}/>{message}</div>}<Page page={page} setPage={setPage} data={data} busy={busy} question={question} setQuestion={setQuestion} ask={ask} answer={answer} transform={transform} version={version} sql={sql} setSql={setSql} validateSql={validateSql} result={result}/></main></div>
}

function Welcome({busy,message,input,upload}) { return <div className="welcome"><header className="landing-head"><div className="brand"><span>P</span>pivot</div><span>Business Intelligence with Memory</span></header><section className="hero"><p className="eyebrow">DATA INTELLIGENCE, NOT DASHBOARDS</p><h1>Understand your data<br/>before you analyze it.</h1><p>Upload a dataset. Pivot profiles it, checks its quality, records its history, and helps you make sense of what is actually there.</p><button className="primary" onClick={()=>input.current.click()}><Upload size={17}/>{busy?'Preparing dataset…':'Upload dataset'}</button><input ref={input} hidden type="file" accept=".csv,.xlsx,.xls,.json,.parquet" onChange={e=>upload(e.target.files?.[0])}/><div className="formats">CSV · Excel · JSON · Parquet</div>{message && <div className="welcome-msg">{busy?<LoaderCircle className="spin" size={18}/>:<ShieldCheck size={18}/>} {message}</div>}</section><section className="journey"><span>Upload</span><i/> <span>Profile</span><i/> <span>Quality</span><i/> <span>Understand</span><i/> <span>Decide</span></section></div> }

function Page({page,setPage,data,busy,question,setQuestion,ask,answer,transform,version,sql,setSql,validateSql,result}) {
  const issues=data.issues||[], schema=data.schema||{}, semantic=schema.semantic_columns||[]
  if(page==='Overview') return <section className="page"><p className="eyebrow">DATASET OVERVIEW</p><h1>{data.file_name}</h1><p className="lede">This is the current source of truth. Pivot has profiled it without changing it.</p><div className="stats"><Card label="Records" value={data.rows.toLocaleString()}/><Card label="Columns" value={data.columns}/><Card label="Data quality" value={`${data.quality_score}/100`}/><Card label="Detected domain" value={data.role}/></div><div className="split"><article className="panel"><h3>What Pivot found</h3><p><b>{semantic.length}</b> fields with semantic meaning</p><p><b>{issues.length}</b> items worth reviewing</p><p><b>{schema.pii_columns?.length||0}</b> potentially sensitive fields</p></article><article className="panel"><h3>Suggested next step</h3><p>Review the profile to confirm what each column means, then resolve any quality issues you agree with.</p><button className="link" onClick={()=>setPage('Profile')}>Open profile <ChevronRight size={15}/></button></article></div><DataTable columns={data.columns_list} rows={data.preview} /></section>
  if(page==='Profile') return <section className="page"><p className="eyebrow">SCHEMA & MEANING</p><h1>Data profile</h1><p className="lede">Pivot’s best understanding of your columns. You can use this to decide what needs correction.</p><div className="table">{semantic.map(x=><div className="row" key={x.column}><b>{x.column}</b><span>{x.role.replaceAll('_',' ')}</span><span>{Math.round(x.confidence*100)}% confident</span><small>{x.evidence}</small></div>)}</div></section>
  if(page==='Quality') return <section className="page"><p className="eyebrow">DATA QUALITY</p><h1>Quality score: {data.quality_score}/100</h1><p className="lede">These are checks, not automatic changes. Review them before you change the dataset.</p><div className="issue-list">{issues.length?issues.map(i=><article className="issue" key={i.type}><b>{i.type.replaceAll('_',' ')}</b><span>{i.count} affected values</span><p>{i.impact}</p><small>Suggested: {i.fix}</small></article>):<article className="issue"><b>No obvious quality issues found</b><p>Pivot did not detect common missing-data, duplicate, date, or outlier issues.</p></article>}</div></section>
  if(page==='Cleaning') return <section className="page"><p className="eyebrow">REVIEW CHANGES</p><h1>Suggested cleanups</h1><p className="lede">Every action creates a separate output. Your uploaded file is never overwritten.</p><div className="cards">{[['trim_text','Trim text fields','Remove accidental spaces around text.'],['remove_duplicates','Remove exact duplicates','Create a clean copy with duplicate rows removed.'],['normalize_columns','Standardize column names','Create safer names for downstream use.'],['parse_dates','Parse date columns','Create typed date fields where safely detected.']].map(([id,name,desc])=><article className="action" key={id}><Wand2 size={19}/><h3>{name}</h3><p>{desc}</p><button className="primary small" disabled={busy} onClick={()=>transform(id)}>{busy?'Working…':'Create clean version'}</button></article>)}</div>{version&&<div className="result"><b>New dataset version ready</b><p>{version.rows_before} → {version.rows_after} records. Review the CSV in Excel or any editor.</p><a className="primary small" href={`${api}/api/datasets/${data.dataset_id}/versions/${version.version}/download`}>Download cleaned CSV</a></div>}</section>
  if(page==='Analysis') return <section className="page"><p className="eyebrow">ANALYSIS READY</p><h1>What can be analyzed</h1><p className="lede">Pivot only offers analyses supported by your dataset’s fields.</p><div className="cards">{[...schema.numeric_columns||[],...schema.date_columns||[]].map(field=><article className="action" key={field}><Sparkles size={19}/><h3>{field}</h3><p>{schema.date_columns?.includes(field)?'Time-based analysis is available.':'Numeric distributions and comparisons are available.'}</p></article>)}</div></section>
  if(page==='AI Analyst') return <section className="page"><p className="eyebrow">GROUNDED ANALYST</p><h1>Ask about this dataset</h1><p className="lede">Ask for an insight or say “write SQL for the top 50 customers by sales.” Pivot shows the generated query and its results.</p><div className="chat"><div className="chat-head"><Bot size={18}/><b>Pivot analyst</b><span>Dataset-aware</span></div>{answer&&<div className="answer"><b>Answer</b><p>{answer.answer}</p>{answer.sql&&<><small>Generated SQL</small><pre>{answer.sql}</pre><b>{answer.query_result.count} rows returned</b><div className="preview"><table><thead><tr>{answer.query_result.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{answer.query_result.rows.map((r,i)=><tr key={i}>{answer.query_result.columns.map(c=><td key={c}>{String(r[c]??'')}</td>)}</tr>)}</tbody></table></div></>}{answer.citations?.length>0&&<small>Sources: {answer.citations.map(x=>x.source).join(', ')}</small>}</div>}<div className="ask"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="For example: Top 50 customers by sales"/><button onClick={ask} disabled={busy}>{busy?'Thinking…':'Ask'}</button></div></div></section>
  if(page==='SQL') return <section className="page"><p className="eyebrow">SAFE SQL WORKSPACE</p><h1>Query this dataset</h1><p className="lede">Use the table name <code>dataset</code>. Only read-only queries are allowed.</p><textarea value={sql} onChange={e=>setSql(e.target.value)}/><button className="primary small" onClick={validateSql} disabled={busy}>{busy?'Running…':'Run query'}</button>{result&&<div className="preview"><h3>{result.count} rows returned</h3><table><thead><tr>{result.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}>{result.columns.map(c=><td key={c}>{String(row[c]??'')}</td>)}</tr>)}</tbody></table></div>}</section>
  if(page==='Reports') return <section className="page"><p className="eyebrow">REPORTS</p><h1>Dataset summary</h1><p className="lede">A concise, traceable summary of this dataset is ready to export.</p><button className="primary" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`${data.file_name}\nRows: ${data.rows}\nColumns: ${data.columns}\nQuality: ${data.quality_score}/100`],{type:'text/plain'}));a.download='pivot-dataset-summary.txt';a.click()}}><FileText size={16}/>Download summary</button></section>
  if(page==='Versions'||page==='Lineage') return <section className="page"><p className="eyebrow">{page.toUpperCase()}</p><h1>{page}</h1><p className="lede">The original upload is the source of truth. Every approved cleanup creates a new, separate version.</p><div className="lineage"><GitBranch size={22}/><div><b>Original source</b><small>{data.file_name} · {data.rows} records · unchanged</small></div></div>{version&&<div className="lineage"><GitBranch size={22}/><div><b>Cleaned version</b><small>{version.rows_after} records · generated from approved transformation</small></div></div>}</section>
  if(page==='Settings') return <section className="page"><p className="eyebrow">WORKSPACE SETTINGS</p><h1>Dataset settings</h1><p className="lede">Your source file stays unchanged. Update the AI key in <code>backend/.env</code>; it is never exposed in the browser.</p><div className="panel"><h3>Current safeguards</h3><p>Original source preserved · transformations versioned · SQL restricted to read-only queries · local metadata store enabled.</p></div></section>
  return <section className="page"><h1>{page}</h1></section>
}
function Card({label,value}){return <article className="stat"><span>{label}</span><b>{value}</b></article>}
export default App
