import { useRef, useState } from 'react'
import { Bot, CheckCircle2, ChevronRight, Database, FileText, GitBranch, LoaderCircle, Play, Search, Settings, ShieldCheck, Sparkles, Upload, Wand2 } from 'lucide-react'

const api = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const nav = ['Overview', 'Profile', 'Quality', 'Cleaning', 'Analysis', 'AI Analyst', 'SQL', 'Reports', 'Versions', 'Lineage']

function App() {
  const [data, setData] = useState(null), [page, setPage] = useState('Overview'), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const [question, setQuestion] = useState(''), [answer, setAnswer] = useState(null), [sql, setSql] = useState('SELECT * FROM dataset LIMIT 20')
  const input = useRef()
  async function upload(file) {
    if (!file) return
    setBusy(true); setMessage('Reading your file and building its data profile…')
    try { const fd = new FormData(); fd.append('file', file); const r = await fetch(`${api}/api/datasets`, { method: 'POST', body: fd }); if (!r.ok) throw new Error('We could not read this file. Try a CSV, Excel, JSON, or Parquet file.'); const result = await r.json(); setData(result); setMessage('Your dataset is ready. Start with its profile or data quality checks.'); setPage('Overview') } catch (e) { setMessage(e.message) } finally { setBusy(false) }
  }
  async function ask() { if (!question.trim()) return; setBusy(true); try { const r = await fetch(`${api}/api/chat`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({question, dataset_id:data.dataset_id, context:{profile:data}}) }); const res = await r.json(); setAnswer(res); setQuestion('') } finally { setBusy(false) } }
  async function transform(operation) { setBusy(true); try { const r = await fetch(`${api}/api/datasets/${data.dataset_id}/transformations/${operation}/execute`, {method:'POST'}); const res = await r.json(); setMessage(res.ok ? `${operation.replace('_',' ')} completed. Your original file is still unchanged.` : 'That action could not be completed.'); } finally { setBusy(false) } }
  async function validateSql() { const r = await fetch(`${api}/api/sql/validate`, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataset_id:data.dataset_id,query:sql})}); const res = await r.json(); setMessage(res.safe ? 'Query is safe and read-only.' : res.detail || 'Query needs review.') }
  if (!data) return <Welcome busy={busy} message={message} input={input} upload={upload}/>
  return <div className="product"><aside><div className="brand"><span>P</span>pivot</div><button className="dataset-switch" onClick={() => {setData(null);setMessage('')}}><Database size={17}/><div><b>{data.file_name}</b><small>{data.rows.toLocaleString()} rows · {data.columns} columns</small></div><ChevronRight size={16}/></button><p className="side-label">DATASET</p><nav>{nav.map(item => <button key={item} className={page===item?'active':''} onClick={()=>setPage(item)}>{item}</button>)}</nav><div className="side-bottom"><button onClick={()=>setPage('Settings')}><Settings size={16}/>Settings</button><small>Everything in Pivot is tied to this dataset.</small></div></aside><main><header><div><p className="eyebrow">ACTIVE DATASET</p><h2>{data.file_name}</h2></div><button className="quiet" onClick={()=>{setData(null);setMessage('')}}>Change dataset</button></header>{message && <div className="notice"><CheckCircle2 size={17}/>{message}</div>}<Page page={page} data={data} busy={busy} question={question} setQuestion={setQuestion} ask={ask} answer={answer} transform={transform} sql={sql} setSql={setSql} validateSql={validateSql}/></main></div>
}

function Welcome({busy,message,input,upload}) { return <div className="welcome"><header className="landing-head"><div className="brand"><span>P</span>pivot</div><span>Business Intelligence with Memory</span></header><section className="hero"><p className="eyebrow">DATA INTELLIGENCE, NOT DASHBOARDS</p><h1>Understand your data<br/>before you analyze it.</h1><p>Upload a dataset. Pivot profiles it, checks its quality, records its history, and helps you make sense of what is actually there.</p><button className="primary" onClick={()=>input.current.click()}><Upload size={17}/>{busy?'Preparing dataset…':'Upload dataset'}</button><input ref={input} hidden type="file" accept=".csv,.xlsx,.xls,.json,.parquet" onChange={e=>upload(e.target.files?.[0])}/><div className="formats">CSV · Excel · JSON · Parquet</div>{message && <div className="welcome-msg">{busy?<LoaderCircle className="spin" size={18}/>:<ShieldCheck size={18}/>} {message}</div>}</section><section className="journey"><span>Upload</span><i/> <span>Profile</span><i/> <span>Quality</span><i/> <span>Understand</span><i/> <span>Decide</span></section></div> }

function Page({page,data,busy,question,setQuestion,ask,answer,transform,sql,setSql,validateSql}) {
  const issues=data.issues||[], schema=data.schema||{}, semantic=schema.semantic_columns||[]
  if(page==='Overview') return <section className="page"><p className="eyebrow">DATASET OVERVIEW</p><h1>{data.file_name}</h1><p className="lede">This is the current source of truth. Pivot has profiled it without changing it.</p><div className="stats"><Card label="Records" value={data.rows.toLocaleString()}/><Card label="Columns" value={data.columns}/><Card label="Data quality" value={`${data.quality_score}/100`}/><Card label="Detected domain" value={data.role}/></div><div className="split"><article className="panel"><h3>What Pivot found</h3><p><b>{semantic.length}</b> fields with semantic meaning</p><p><b>{issues.length}</b> items worth reviewing</p><p><b>{schema.pii_columns?.length||0}</b> potentially sensitive fields</p></article><article className="panel"><h3>Suggested next step</h3><p>Review the profile to confirm what each column means, then resolve any quality issues you agree with.</p><button className="link">Open profile <ChevronRight size={15}/></button></article></div></section>
  if(page==='Profile') return <section className="page"><p className="eyebrow">SCHEMA & MEANING</p><h1>Data profile</h1><p className="lede">Pivot’s best understanding of your columns. You can use this to decide what needs correction.</p><div className="table">{semantic.map(x=><div className="row" key={x.column}><b>{x.column}</b><span>{x.role.replaceAll('_',' ')}</span><span>{Math.round(x.confidence*100)}% confident</span><small>{x.evidence}</small></div>)}</div></section>
  if(page==='Quality') return <section className="page"><p className="eyebrow">DATA QUALITY</p><h1>Quality score: {data.quality_score}/100</h1><p className="lede">These are checks, not automatic changes. Review them before you change the dataset.</p><div className="issue-list">{issues.length?issues.map(i=><article className="issue" key={i.type}><b>{i.type.replaceAll('_',' ')}</b><span>{i.count} affected values</span><p>{i.impact}</p><small>Suggested: {i.fix}</small></article>):<article className="issue"><b>No obvious quality issues found</b><p>Pivot did not detect common missing-data, duplicate, date, or outlier issues.</p></article>}</div></section>
  if(page==='Cleaning') return <section className="page"><p className="eyebrow">REVIEW CHANGES</p><h1>Suggested cleanups</h1><p className="lede">Every action creates a separate output. Your uploaded file is never overwritten.</p><div className="cards">{[['trim_text','Trim text fields','Remove accidental spaces around text.'],['remove_duplicates','Remove exact duplicates','Create a clean copy with duplicate rows removed.'],['normalize_columns','Standardize column names','Create safer names for downstream use.'],['parse_dates','Parse date columns','Create typed date fields where safely detected.']].map(([id,name,desc])=><article className="action" key={id}><Wand2 size={19}/><h3>{name}</h3><p>{desc}</p><button className="primary small" disabled={busy} onClick={()=>transform(id)}>Create clean version</button></article>)}</div></section>
  if(page==='Analysis') return <section className="page"><p className="eyebrow">ANALYSIS READY</p><h1>What can be analyzed</h1><p className="lede">Pivot only offers analyses supported by your dataset’s fields.</p><div className="cards">{[...schema.numeric_columns||[],...schema.date_columns||[]].map(field=><article className="action" key={field}><Sparkles size={19}/><h3>{field}</h3><p>{schema.date_columns?.includes(field)?'Time-based analysis is available.':'Numeric distributions and comparisons are available.'}</p></article>)}</div></section>
  if(page==='AI Analyst') return <section className="page"><p className="eyebrow">GROUNDED ANALYST</p><h1>Ask about this dataset</h1><p className="lede">Answers are based on the active dataset and show when evidence is limited.</p><div className="chat"><div className="chat-head"><Bot size={18}/><b>Pivot analyst</b><span>Dataset-aware</span></div>{answer&&<div className="answer"><b>Answer</b><p>{answer.answer}</p>{answer.citations?.length>0&&<small>Sources: {answer.citations.map(x=>x.source).join(', ')}</small>}</div>}<div className="ask"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="For example: What fields are available?"/><button onClick={ask} disabled={busy}>Ask</button></div></div></section>
  if(page==='SQL') return <section className="page"><p className="eyebrow">SAFE SQL WORKSPACE</p><h1>Validate a read-only query</h1><p className="lede">Pivot blocks commands that could alter data. External database execution is not enabled in this local build.</p><textarea value={sql} onChange={e=>setSql(e.target.value)}/><button className="primary small" onClick={validateSql}>Validate query</button></section>
  if(page==='Reports') return <section className="page"><p className="eyebrow">REPORTS</p><h1>Dataset summary</h1><p className="lede">A concise, traceable summary of this dataset is ready to export.</p><button className="primary" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`${data.file_name}\nRows: ${data.rows}\nColumns: ${data.columns}\nQuality: ${data.quality_score}/100`],{type:'text/plain'}));a.download='pivot-dataset-summary.txt';a.click()}}><FileText size={16}/>Download summary</button></section>
  if(page==='Versions'||page==='Lineage') return <section className="page"><p className="eyebrow">{page.toUpperCase()}</p><h1>{page}</h1><p className="lede">The original upload is the source of truth. Every approved cleanup creates a new, separate version.</p><div className="lineage"><GitBranch size={22}/><div><b>Original source</b><small>{data.file_name} · {data.rows} records · unchanged</small></div></div></section>
  return <section className="page"><h1>{page}</h1></section>
}
function Card({label,value}){return <article className="stat"><span>{label}</span><b>{value}</b></article>}
export default App
